management:
   endpoints.web.exposure.include:  '*'
   endpoint :
      health.show-details : always
      
spring :
    http.log-request-details : true      
               
virus.enabled : true         