wonderwall:
  ingress: https://foreldrepengesoknad.intern.dev.nav.no,
    https://foreldrepenger.intern.dev.nav.no,
    https://svangerskapspengesoknad.intern.dev.nav.no,
    https://engangsstonad.intern.dev.nav.no

allowed:
  origins:
    https://engangsstonad.dev.nav.no,
    https://engangsstonad.intern.dev.nav.no,
    https://foreldrepenger.dev.nav.no,
    https://foreldrepenger.intern.dev.nav.no,
    https://foreldrepengesoknad.dev.nav.no,
    https://foreldrepengesoknad.intern.dev.nav.no,
    https://svangerskapspengesoknad.dev.nav.no,
    https://svangerskapspengesoknad.intern.dev.nav.no,
    https://foreldrepengesoknad-api.dev.nav.no,
    https://foreldrepengesoknad-api.intern.dev.nav.no

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring:
  mvc:
    log-request-details: true

virus:
  uri: http://clamav.nais-system/scan

no.nav:
  security:
    jwt:
      client:
        registration:
          fpsoknad-mottak:
            token-exchange:
              audience: dev-fss:teamforeldrepenger:fpsoknad-mottak
          fpinfo-historikk:
            token-exchange:
              audience: dev-fss:teamforeldrepenger:fpinfo-historikk
          fpoversikt:
            token-exchange:
              audience: dev-gcp:teamforeldrepenger:fpoversikt
          safselvbetjening:
            token-exchange:
              audience: dev-fss:teamdokumenthandtering:safselvbetjening
      issuer:
        selvbetjening:
          discoveryurl: https://navtestb2c.b2clogin.com/navtestb2c.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten_ver1
          accepted_audience: 9ecf7c8f-4efd-466d-b864-97fe3571b160
          cookie_name: selvbetjening-idtoken

oppslag:
  uri: https://fpsoknad-mottak.dev-fss-pub.nais.io/api/
historikk:
  uri: https://fpinfo-historikk.dev-fss-pub.nais.io/api/
mottak:
  uri: https://fpsoknad-mottak.dev-fss-pub.nais.io/api/
minidialog:
  uri: https://fpinfo-historikk.dev-fss-pub.nais.io/api/
fppdfgen:
  uri: http://fppdfgen
oversikt:
  uri: http://fpoversikt
safselvbetjening:
  baseUri: https://safselvbetjening.dev-fss-pub.nais.io
