allowed.origins: '*'
debug: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
server:
  port: 9002
spring:
  mvc:
    log-request-details: true

no.nav.security.jwt:
  client:
    registration:
      fpsoknad-mottak:
        token-exchange:
          audience: lokal
      fpinfo-historikk:
        token-exchange:
          audience: lokal
      fpoversikt:
        token-exchange:
          audience: lokal

virus:
  enabled: false
fppdfgen:
  enabled: false
historikk:
  uri: ${fpinfo-historikk.override.url}
minidialog:
  uri: ${fpinfo-historikk.override.url}
mottak:
  uri: ${fpsoknad-mottak.override.url}
oppslag:
  uri: ${fpsoknad-mottak.override.url}
oversikt:
  uri: ${fpoversikt.override.url}
storage:
  passphrase: tullogt√∏ys
