allowed:
  origins:
    https://engangsstonad.nav.no,
    https://foreldrepenger.nav.no,
    https://foreldrepengesoknad.nav.no,
    https://svangerskapspengesoknad.nav.no

no.nav:
  security:
    jwt:
      dont-propagate-bearertoken: false
      client:
        registration:
          fpsoknad-mottak:
            well-known-url: ${token.x.well.known.url}
            grant-type: urn:ietf:params:oauth:grant-type:token-exchange
            authentication:
              client-id: ${token.x.client.id}
              client-jwk: ${token.x.private.jwk}
              client-auth-method: private_key_jwt
          fpinfo-historikk:
            well-known-url: ${token.x.well.known.url}
            grant-type: urn:ietf:params:oauth:grant-type:token-exchange
            authentication:
              client-id: ${token.x.client.id}
              client-jwk: ${token.x.private.jwk}
              client-auth-method: private_key_jwt
          fpoversikt:
            well-known-url: ${token.x.well.known.url}
            grant-type: urn:ietf:params:oauth:grant-type:token-exchange
            authentication:
              client-id: ${token.x.client.id}
              client-jwk: ${token.x.private.jwk}
              client-auth-method: private_key_jwt
          safselvbetjening:
            well-known-url: ${token.x.well.known.url}
            grant-type: urn:ietf:params:oauth:grant-type:token-exchange
            authentication:
              client-id: ${token.x.client.id}
              client-jwk: ${token.x.private.jwk}
              client-auth-method: private_key_jwt
      issuer:
        selvbetjening:
          discoveryurl: ${loginservice.idporten.discovery.url}
          accepted_audience: ${loginservice.idporten.audience}
          cookie_name: selvbetjening-idtoken

virus:
  enabled: true

management:
  health:
    refresh:
      enabled: false
    diskspace:
      enabled: false
  endpoint:
    health:
      show-details: never
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
      base-path: /internal/actuator
server:
  servlet:
    context-path: /
  forward-headers-strategy: native
spring:
  cloud.discovery.enabled: false
  cache:
    cache-names: akt√∏r
    caffeine:
      spec: maximumSize=100,expireAfterAccess=3600s
  application:
    name: foreldrepengesoknad-api
  main:
    banner-mode: 'off'
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    throw-exception-if-no-handler-found: true
springdoc:
  packages-to-scan: no.nav.foreldrepenger.selvbetjening
  swagger-ui:
    disable-swagger-default-url: true
