allowed:
  origins:
    https://engangsstonad.nav.no,
    https://foreldrepenger.nav.no,
    https://foreldrepengesoknad.nav.no,
    https://svangerskapspengesoknad.nav.no,
    https://foreldrepengesoknad-api.nav.no,

mellomlagring:
  tmp:
    navn: mellomlagring-prod

virus:
  uri: http://clamav.nais-system/scan

no.nav:
  security:
    jwt:
      client:
        registration:
          fpsoknad-mottak:
            token-exchange:
              audience: prod-fss:teamforeldrepenger:fpsoknad-mottak
          fpinfo-historikk:
            token-exchange:
              audience: prod-fss:teamforeldrepenger:fpinfo-historikk
          fpoversikt:
            token-exchange:
              audience: prod-gcp:teamforeldrepenger:fpoversikt
          safselvbetjening:
            token-exchange:
              audience: prod-fss:teamdokumenthandtering:safselvbetjening

oppslag:
  uri: https://fpsoknad-mottak.prod-fss-pub.nais.io/api/
historikk:
  uri: https://fpinfo-historikk.prod-fss-pub.nais.io/api/
mottak:
  uri: https://fpsoknad-mottak.prod-fss-pub.nais.io/api/
minidialog:
  uri: https://fpinfo-historikk.prod-fss-pub.nais.io/api/
fppdfgen:
  uri: http://fppdfgen
oversikt:
  uri: http://fpoversikt
safselvbetjening:
  baseUri: https://safselvbetjening.prod-fss-pub.nais.io
