allowed:
  origins:
   https://engangsstonad.dev.nav.no,
   https://foreldrepengesoknad.dev.nav.no,
   https://foreldrepengesoknad.dev.adeo.no,
   https://svangerskapspengesoknad.dev.nav.no,
   https://foreldrepenger.dev.nav.no,
   https://engangsstonad.dev.nav.no,
   https://foreldrepengesoknad.dev.nav.no,
   https://svangerskapspengesoknad.dev.nav.no,
   https://foreldrepenger.dev.nav.no
spring:
  cloud:
    vault:
      enabled: false
      
mellomlagring:
  tmp:
    navn: foreldrepengesoknad-prod
  s√∏knad:
     navn: mellomlagring-prod   
   
virus:
   uri: http://clamav.clamav/scan
